// Generated by CoffeeScript 1.6.3
(function() {
  var ConstructorUndefined, FactoryError, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  FactoryError = require('./FactoryError');

  ConstructorUndefined = (function(_super) {
    __extends(ConstructorUndefined, _super);

    function ConstructorUndefined() {
      _ref = ConstructorUndefined.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ConstructorUndefined.prototype.setDefaults = function() {
      if (this.message == null) {
        this.message = "Constructor is undefined.";
      }
      return ConstructorUndefined.__super__.setDefaults.call(this);
    };

    return ConstructorUndefined;

  })(FactoryError);

  module.exports = ConstructorUndefined;

}).call(this);

/*
//@ sourceMappingURL=ConstructorUndefined.map
*/
