// Generated by CoffeeScript 1.6.3
(function() {
  var CommandNotRegistered, CustomError, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CustomError = require('boco-error').CustomError;

  CommandNotRegistered = (function(_super) {
    __extends(CommandNotRegistered, _super);

    function CommandNotRegistered() {
      _ref = CommandNotRegistered.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    CommandNotRegistered.prototype.constructPayload = function(params) {
      if (params == null) {
        params = {};
      }
      return {
        name: params.name
      };
    };

    return CommandNotRegistered;

  })(CustomError);

  module.exports = CommandNotRegistered;

}).call(this);

/*
//@ sourceMappingURL=ConstructorNotRegistered.map
*/
