// Generated by CoffeeScript 1.6.3
(function() {
  var CustomError, FactoryError, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CustomError = require('boco-error').CustomError;

  FactoryError = (function(_super) {
    __extends(FactoryError, _super);

    function FactoryError() {
      _ref = FactoryError.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return FactoryError;

  })(CustomError);

  module.exports = FactoryError;

}).call(this);

/*
//@ sourceMappingURL=FactoryError.map
*/
