// Generated by CoffeeScript 1.6.3
(function() {
  exports.FactoryError = require('./FactoryError');

  exports.ConstructorUndefined = require('./ConstructorUndefined');

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
